managed_servers = %w( 192.168.10.80 192.168.10.81 192.168.10.82 192.168.10.83 )

Vagrant.configure(2) do |config|
  config.orchestrate.credentials.prompt = true

  managed_servers.each_with_index do |server, index|
    config.vm.define "managed-#{index+1}" do |managed|
      managed.vm.provision "shell", inline: "echo 'hello world'"
      managed.vm.box = "managed-server-dummy"
      managed.vm.box_url = "./dummy.box"
#      managed.ssh.password = "vagrant"
      managed.vm.provider :managed do |provider|
        provider.server = server
      end
    end
  end
end
