managed_servers = %w( 192.168.10.80 192.168.10.81 192.168.10.82 192.168.10.83 )

Vagrant.configure(2) do |config|
  # Print a unique string that we can check the output for
  config.vm.provision :shell, inline: "echo 6etrabEmU8ru8hapheph"

  managed_servers.each_with_index do |server, index|
    config.vm.define "managed-#{index + 1}" do |managed|
      managed.vm.provision "shell", inline: "echo 'hello world'"
      managed.vm.box = "managed-server-dummy"
      managed.vm.box_url = "./dummy.box"
      managed.ssh.password = "vagrant"
      managed.vm.provider :managed do |provider|
        provider.server = server
      end
    end
  end
end
